name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install library
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
          pip install pytest pytest-cov
      - name: Run code coverage
        run: |
          pytest --cov-branch --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
           token: ${{ secrets.CODECOV_TOKEN }}
