name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install library
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Generate Report
        run: |
          pip install coverage
          coverage run -m pytest
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
