name: Formatting checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check_formatting:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install library
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Check imports with isort
      run: |
        isort --check .
    - name: Check formatting with black
      run: |
        black --check .
