name: Pytest tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest_tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install library
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Run tests
      run: |
        python -m pytest tests
